### ISSUE TITLE
Ratelimit for create_tweet

### ISSUE THREAD

**Issue by t1mp4** [d60/twikit#185]
What is the ratelimit for create_tweet? It is not specified in ratelimits.md.

**Comment by d60** [comment]
it's unknown

**Comment by DuffyAdams** [comment]
is it unknown because twitter/X sets whatever limit they feel like at any given time? If so, do you know any work arounds?
I'm currently getting this error.

raise CouldNotTweet( twikit.errors.CouldNotTweet: {'message': 'Authorization: You have reached your daily limit for sending Tweets and messages. Please try again later. (344)', 'locations': [{'line': 18, 'column': 3}], 'path': ['create_tweet'], 'extensions': {'name': 'AuthorizationError', 'source': 'Client', 'code': 344, 'kind': 'Permissions', 'tracing': {'trace_id': 'afbdf9d309b61bc1'}}, 'code': 344, 'kind': 'Permissions', 'name': 'AuthorizationError', 'source': 'Client', 'tracing': {'trace_id': 'afbdf9d309b61bc1'}}

I tweet about once every 15 minutes
