### ISSUE TITLE
 ERROR:  self.attachment: str | None = attachment['media_url_https'] KeyError: 'media_url_https'

### ISSUE THREAD

**Issue by devilevil100** [d60/twikit#20]
To reproduce:  tweet is shared in group chat.

**Comment by d60** [comment]
Thank you.

First, I changed message.attachment to directly include the attachment information returned from the API, instead of including the URL as before. I think this solved the problem in #20.
https://github.com/d60/twikit/commit/8fe6512549208ccd591a34a10bd58efab917ca27

However, for images, none of the URLs in the information seem to work. I also could not find a way to access these images.
