### ISSUE TITLE
It seems that Twitter has changed its API, causing await client.user() to return a 404 error.

### ISSUE THREAD

**Issue by IronEaterBeast** [d60/twikit#263]
My program used to run perfectly fine, but today I encountered the following error. I suspect that Twitter has changed its API. What do you think?

File "D:\ljtCodingWorks\PythonWorks\TwitterSpy\run.py", line 249, in <module>
    asyncio.run(whileMain())
  File "D:\ProgramData\Anaconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\ljtCodingWorks\PythonWorks\TwitterSpy\run.py", line 243, in whileMain
    await main()
  File "D:\ljtCodingWorks\PythonWorks\TwitterSpy\run.py", line 187, in main
    my = await client.user()
         ^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\site-packages\twikit\client\client.py", line 621, in user
    return await self.get_user_by_id(await self.user_id())
                                     ^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\site-packages\twikit\client\client.py", line 612, in user_id
    response, _ = await self.v11.settings()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\site-packages\twikit\client\v11.py", line 102, in settings
    return await self.base.get(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\site-packages\twikit\client\client.py", line 178, in get
    return await self.request('GET', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\Lib\site-packages\twikit\client\client.py", line 162, in request
    raise NotFound(message, headers=response.headers)
twikit.errors.NotFound: status: 404, message: "{"errors":[{"message":"Sorry, that page does not exist","code":34}]}"

**Comment by oliverpk2000** [comment]
getting this error as well, current workaround for me is to use `client.get_user_by_screen_name()`. However, I am not sure if this will get all information for your program.

**Comment by IronEaterBeast** [comment]
> getting this error as well, current workaround for me is to use `client.get_user_by_screen_name()`. However, I am not sure if this will get all information for your program.

I'm currently researching the reason for this issue, yes, client.get_user_by_screen_name() is a feasible alternative solution.

**Comment by runetech0** [comment]
Just adding more info to the issue here.
I have my own complete wrapper for the X/Twitter API which has been working fine for years and I was keeping it updated. Twitter had added a new header called 'x-client-transaction-id' few months ago but it had no breaking effect until the last week. Now if you send requests without 'x-client-transaction-id' header you get the following error.

`{'errors': [{'message': 'Sorry, that page does not exist', 'code': 34}]}`


I have been researching on this issue for days and I found this great blog about this header https://antibot.blog/twitter/ .

The guy has already done the hard work of reverse engineering the obfuscated code that generates the 'x-client-transaction-id' header. 
[Here's a repo](https://github.com/yeyuchen198/twitter-tid-generator) probably from the author of the [blog I mention above](https://antibot.blog/twitter/) which has the GO code that generates the 'x-client-transaction-id' header. 

I'm not a GO developer so I don't understand the code in the repo but from the blog I know it's an API that can generate 'x-client-transaction-id' header. I I somehow setup the API  on my local machine and generated the 'x-client-transaction-header' but that value doesn't work. Probably because that code was written in Jan-2024 and Twitter has made some changes again.

May be someone can use this info and create a working 'x-client-transaction-id' header.
This header (I suppose) is gonna break almost all the endpoints in the near future if we can't figure out how to properly generate this header.
If anyone wants to help with this, my telegram is [@runetech](https://t.me/runetech).
If I ever figure that out then I'll post the python converted code here or probably open a PR. 

Sorry for my bad explanation!

**Comment by d60** [comment]
try version 2.2.0 everyone
